### ISSUE TITLE
unsupported operand type(s) for /: 'float' and 'str'

### ISSUE THREAD

**Issue by jhg-tgu** [mgedmin/objgraph#27]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/env/lib/python3.4/site-packages/objgraph.py", line 506, in show_refs
    shortnames=shortnames, output=output)
  File "/opt/env/lib/python3.4/site-packages/objgraph.py", line 667, in _show_graph
    h, s, v = _gradient((0, 0, 1), (0, 0, .3), tdepth, max_depth)
  File "/opt/env/lib/python3.4/site-packages/objgraph.py", line 867, in _gradient
    f = float(depth) / max_depth
TypeError: unsupported operand type(s) for /: 'float' and 'str'
```

**Comment by mgedmin** [comment]
Can you tell me what you did to trigger this?

From the tracebacks it looks like you called `show_refs(..., max_depth='a string of some kind')`?
